use indicatif::ProgressBar;

use crate::ai::AiService;
use crate::error::NutsError;
use crate::mcp::client::McpClient;
use crate::mcp::types::Tool;
use crate::output::renderer;

/// AI-generate a YAML test suite from discovered MCP server schemas.
///
/// Connects to the server via `client`, discovers all tools, then asks the AI
/// to produce test cases for each tool. Returns the combined YAML string.
pub async fn generate_tests(client: &McpClient, ai: &AiService) -> Result<String, NutsError> {
    // 1. Discover tools
    let spinner = ProgressBar::new_spinner();
    spinner.set_style(renderer::spinner_style());
    spinner.set_message("Discovering tools...");
    spinner.enable_steady_tick(std::time::Duration::from_millis(80));

    let tools = client.list_tools().await?;
    spinner.finish_and_clear();

    if tools.is_empty() {
        renderer::render_section(
            "MCP Generate",
            "No tools found on the server. Nothing to generate.",
        );
        return Ok(String::new());
    }

    eprintln!(
        "  Found {} tool(s). Generating test cases...\n",
        tools.len()
    );

    // 2. For each tool, call AI to generate test cases
    let mut all_test_yaml_sections: Vec<String> = Vec::new();

    for (i, tool) in tools.iter().enumerate() {
        let label = format!(
            "[{}/{}] Generating tests for '{}'...",
            i + 1,
            tools.len(),
            tool.name
        );

        let spinner = ProgressBar::new_spinner();
        spinner.set_style(renderer::spinner_style());
        spinner.set_message(label);
        spinner.enable_steady_tick(std::time::Duration::from_millis(80));

        let yaml_section = generate_for_tool(ai, tool).await?;
        spinner.finish_and_clear();

        if !yaml_section.is_empty() {
            all_test_yaml_sections.push(yaml_section);
        }
    }

    // 3. Combine into a single YAML test file with a header
    let combined = build_test_file(&tools, &all_test_yaml_sections);
    Ok(combined)
}

/// Generate test cases for a single tool via the AI service.
async fn generate_for_tool(ai: &AiService, tool: &Tool) -> Result<String, NutsError> {
    let description = tool.description.as_deref().unwrap_or("(no description)");

    let schema_str = tool
        .input_schema
        .as_ref()
        .map(|v| serde_json::to_string_pretty(v).unwrap_or_else(|_| "{}".to_string()))
        .unwrap_or_else(|| "{}".to_string());

    let ai_response = ai
        .generate_test_cases(&tool.name, description, &schema_str)
        .await
        .map_err(|e| NutsError::Ai {
            message: format!("AI test generation for '{}' failed: {}", tool.name, e),
        })?;

    // The AI returns a YAML array. Strip any markdown fences if present.
    Ok(strip_yaml_fences(&ai_response))
}

/// Combine individual tool test sections into a complete YAML test file.
fn build_test_file(tools: &[Tool], sections: &[String]) -> String {
    let mut out = String::new();

    // Header comment
    out.push_str("# Auto-generated MCP test suite\n");
    out.push_str("# Generated by: nuts mcp generate\n");
    out.push_str(&format!(
        "# Tools covered: {}\n",
        tools
            .iter()
            .map(|t| t.name.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("#\n");
    out.push_str("# Run with: nuts mcp test <this-file> --stdio \"<server-command>\"\n\n");

    out.push_str("tests:\n");

    for section in sections {
        // Each section is a YAML array (lines starting with "- ").
        // Indent each line by 2 spaces under `tests:`.
        for line in section.lines() {
            out.push_str("  ");
            out.push_str(line);
            out.push('\n');
        }
        out.push('\n');
    }

    out
}

/// Strip markdown YAML fences that the AI might wrap around the response.
fn strip_yaml_fences(text: &str) -> String {
    let trimmed = text.trim();

    // Remove opening ```yaml or ``` fence
    let without_open = if trimmed.starts_with("```yaml") {
        trimmed
            .strip_prefix("```yaml")
            .unwrap_or(trimmed)
            .trim_start()
    } else if trimmed.starts_with("```yml") {
        trimmed
            .strip_prefix("```yml")
            .unwrap_or(trimmed)
            .trim_start()
    } else if trimmed.starts_with("```") {
        trimmed.strip_prefix("```").unwrap_or(trimmed).trim_start()
    } else {
        trimmed
    };

    // Remove closing ``` fence
    let without_close = if without_open.ends_with("```") {
        without_open
            .strip_suffix("```")
            .unwrap_or(without_open)
            .trim_end()
    } else {
        without_open
    };

    without_close.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_yaml_fences_removes_fences() {
        let input = "```yaml\n- name: test\n  tool: foo\n```";
        let result = strip_yaml_fences(input);
        assert_eq!(result, "- name: test\n  tool: foo");
    }

    #[test]
    fn strip_yaml_fences_handles_no_fences() {
        let input = "- name: test\n  tool: foo";
        let result = strip_yaml_fences(input);
        assert_eq!(result, "- name: test\n  tool: foo");
    }

    #[test]
    fn strip_yaml_fences_handles_yml_fence() {
        let input = "```yml\n- name: test\n```";
        let result = strip_yaml_fences(input);
        assert_eq!(result, "- name: test");
    }

    #[test]
    fn strip_yaml_fences_handles_plain_fence() {
        let input = "```\n- name: test\n```";
        let result = strip_yaml_fences(input);
        assert_eq!(result, "- name: test");
    }

    #[test]
    fn build_test_file_combines_sections() {
        let tools = vec![
            Tool {
                name: "search".into(),
                description: Some("Search docs".into()),
                input_schema: None,
            },
            Tool {
                name: "create".into(),
                description: None,
                input_schema: None,
            },
        ];

        let sections = vec![
            "- name: \"search test\"\n  tool: \"search\"\n  input:\n    query: \"hello\"".into(),
            "- name: \"create test\"\n  tool: \"create\"\n  input: {}".into(),
        ];

        let result = build_test_file(&tools, &sections);
        assert!(result.contains("# Auto-generated MCP test suite"));
        assert!(result.contains("Tools covered: search, create"));
        assert!(result.contains("tests:"));
        assert!(result.contains("  - name: \"search test\""));
        assert!(result.contains("  - name: \"create test\""));
    }
}
